FROM centos:7.9.2009
RUN yum -y install epel-release && yum -y install python Lmod
RUN yum -y install bzip2 diffutils file gcc-c++ git gzip make openssl-devel rdma-core-devel patch tar unzip xz
RUN yum -y update ca-certificates
